### ISSUE TITLE
[HubMovement] 허브간 이동 정보

### ISSUE THREAD

**Issue by Krystal-13** [ForJJJ/DeliverySystem#43]

**Comment by Krystal-13** [comment]
허브가 생성될 때, 허브 간 이동 정보를 어떤 방식으로 생성하고 저장할지는.. 좀 더 고민하고 있습니다.
의견이나 조언이 있다면 공유부탁드려요 🙏🏻

**Comment by jiminchur** [comment]
제가 생각한 방법은 우선 처음에는 네이버 길찾기를 이용하여 예상 거리 예상 시간을 적어두고 추후에 실제로 배달이 되면 실제로 걸린 시간을 기입하는 방법입니다.예시로는  A -> B까지 걸린 시간이 네이버 길찾기 기준 10분이라면 우선 10분으로 작성해두고 저희가 실제로 배송이 되어 걸린 시간을 새롭게 갱신되게 하는 것 입니다. 좀 또 다른 방법으로는 일주일 단위 혹은 한달 단위로 실제로 걸린 시간의 평균을 넣거나 하는 방법도 있을거 같긴 합니다.

**Comment by Krystal-13** [comment]
오! 맞습니다.. 현재 Naver API 로 예상 시간을 가져오고있습니다!
그런데 제 1 허브에서 나머지 n - 1 개의 허브에 대한 모든 예상 시간을 저장하는게 좋을지에 대한 부분을 고민중이었습니다😵‍💫
일단 초기 요구사항이 허브 17개이며, 이동 가능 방향이 2개로 정해져 있었습니다. 
추가로 허브가 추가 된다 하더라도 기존에 있는 모든 허브에 대한 이동 정보를 추가하더라도 부담이 되지 않는다는 생각이 들어서.. 
현재는 추가된 허브에서 기존 저장된 모든 허브에 대한 이동 경로 정보를 저장하는 시나리오로 만들었습니다.

그리고, 마지막에 의견주신 일주일 단위 혹은 한달 단위로 걸린 시간의 평균을 예상 값으로 넣는 로직도 너무 괜찮은 방법이라 추후 리팩토링으로 고민해보겠습니다!!
의견 감사합니다 👍🏻
